# Generated by Django 5.0.6 on 2024-10-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_servicetype_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
