# Generated by Django 5.0.6 on 2024-10-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='image',
            field=models.ImageField(upload_to='media/ProjectImages'),
        ),
    ]
