# Generated by Django 5.0.6 on 2024-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutus_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='text',
            field=models.TextField(),
        ),
    ]
